version: '3.8'

services:
  laravel-app:
    build:
      context: .
    container_name: laravel-api-container
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
      - dbdata:/var/lib/mysql

    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge
